#include <iostream>

int main() {
    try {
        int numerator = 10;
        int denominator = 0;
        int result = numerator / denominator;
        int x = 5;
        int y = 0;
        int divisionResult = x / y;
        
        std::cout << "Результат: " << result << std::endl;
    } 
    catch (const std::exception& e) {
        std::cout << "Ошибка деления на 0: " << e.what() << std::endl;
    }

    return 0;
}